# Use official base image running latest Node.js v8 LTS on Debian Linux.
# node:8.14-slim (https://github.com/docker-library/repo-info/blob/master/repos/node/remote/8.14-slim.md) 
FROM node@sha256:3a97081f14a07ad5fd07f26ffcd0573ceaabf4682df19e24e455d95b4b56a53d

# Set operational and environment variables:
EXPOSE 80
ENV PORT 80

# Set the default executable for the image:
CMD [ "npm", "run", "server" ]

# Set the working directory to /app
WORKDIR ./app

# Copy package required files:
COPY package.json package-lock.json ./

# Install packages:
RUN npm ci --quiet && npm cache clean --force && \
    rm -rf /tmp/*

# Set production mode:
ENV NODE_ENV production

# Copy all files in current directory to image:
COPY ./ ./

# Remove secret file and run all commands:
RUN npm run build 